### ISSUE TITLE
How to Track conversion id

### ISSUE THREAD

**Issue by nettemsarath** [floriangaechter/gatsby-plugin-linkedin-insight#1]
I added this plugin but how to track particular conversion id

import LinkedInTag from 'react-linkedin-insight';
LinkedInTag.init(partnerId);
LinkedInTag.track(conversionId)
If we use that react module we can but how to do in hasty with ur plugin..
 Also I can see the events facebook and gtag with chrome extensioms , is there any extension for this plugin to check that are executicting

**Comment by floriangaechter** [comment]
Hey there. Sorry for the late reply. Please consider using this fork of the plugin: https://github.com/tmttn/gatsby-plugin-linkedin-insight.
